/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlightning_JlightningClient */

#ifndef _Included_jlightning_JlightningClient
#define _Included_jlightning_JlightningClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jlightning_JlightningClient
 * Method:    connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jlightning_JlightningClient_connect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jlightning_JlightningClient
 * Method:    create
 * Signature: (JJI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_jlightning_JlightningClient_create
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     jlightning_JlightningClient
 * Method:    seal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_seal
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jlightning_JlightningClient
 * Method:    get
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_jlightning_JlightningClient_get
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jlightning_JlightningClient
 * Method:    release
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_release
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jlightning_JlightningClient
 * Method:    delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_delete
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jlightning_JlightningClient
 * Method:    multiput
 * Signature: (JJ[Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_multiput
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jobjectArray);

/*
 * Class:     jlightning_JlightningClient
 * Method:    multiupdate
 * Signature: (JJ[Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_multiupdate
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jobjectArray);

/*
 * Class:     jlightning_JlightningClient
 * Method:    multiget
 * Signature: (JJ[Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_jlightning_JlightningClient_multiget
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     jlightning_JlightningClient
 * Method:    getbyte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_jlightning_JlightningClient_getbyte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jlightning_JlightningClient
 * Method:    getbytes
 * Signature: ([BJJJ)V
 */
JNIEXPORT void JNICALL Java_jlightning_JlightningClient_getbytes
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
